name: Deploy

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/mcp-widget-app
            git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/muhammad-uzair-yasin/mcp-widget-app.git
            git pull origin master
            git remote set-url origin https://github.com/muhammad-uzair-yasin/mcp-widget-app.git
            npm install
            npm run build
